# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MovieApp' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'
    
    pod 'React', path: '../node_modules/react-native'
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    ]
#    pod 'DoubleConversionx', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    # If you are using React Native <0.54, you will get the following error:
    # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
    # Use the following line instead:
    #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    
    pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end
  
post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        
        # The following is needed to ensure the "archive" step works in XCode.
        # It removes React & Yoga from the Pods project, as it is already included in the main project.
        # Without this, you'd see errors when you archive like:
        # "Multiple commands produce ... libReact.a"
        # "Multiple commands produce ... libyoga.a"
        
        targets_to_ignore = %w(React yoga)
        
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
        
    end
end
